# Generated by Django 6.0.6 on 2026-06-04 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(max_length=500)),
                ('video_title', models.CharField(blank=True, max_length=300, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('tone_analysis', models.CharField(blank=True, max_length=150, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=300, null=True)),
                ('suggested_titles', models.JSONField(blank=True, default=list, null=True)),
                ('seo_tags', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Video Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
